@echo off
echo Starting Contra.AI...
echo Starting Backend (Flask)...
start "Contra Backend" cmd /c "cd backend && python app.py"
echo Waiting for backend to initialize...
timeout /t 5 >nul
echo Starting Frontend (Vite)...
start "Contra Frontend" cmd /c "npm run dev"
echo Waiting for frontend to initialize...
timeout /t 5 >nul
echo Opening Browser...
start http://localhost:5173
echo Done! Application is running.
pause
